### PR TITLE
Fix deployment API version

### PR DESCRIPTION
**Pull request by RobertKrawitz**
Deployments are part of the standard apps API.

### CODE REVIEW

**Comment by dustinblack** [comment]
I haven't tested -- Can anyone confirm that this change won't break only older API version?

**Comment by mffiedler** [comment]
apps/v1 was introduced in 1.9 (OCP 3.9).   So, all supported versions of OCP understand apps/v1.

**Comment by mffiedler** [comment]
Can we please merge this?   Keep having to change this when cloning dittybopper.   Minor but annoying.    /cc: @aakarshg

**Pull request merged**
